services:
  app:
    build: .
    ports:
      - "8088:80"
    restart: always
    depends_on:
      - time_app
    networks:
      - back
  time_app:
    build: ../TimeApp
    networks:
      - back
networks:
  back:
    driver: bridge